<?php echo $this->render('header.phtml'); ?>

	<h1 class="block"><?php echo $this->escape($this->title); ?></h1>        
        <div class="column1-unit">
	    <?php if(! empty($this->message)) { ?>
          <h2><?php echo $this->escape($this->message);?></h2>
        <?php } else {?>
	    <br />
        <?php }?>
          <div class="loginform">
            <form method="post" action="<?php echo $this->baseUrl ?>/auth/login"> 
              <fieldset>
                <p><label for="username" class="top">Login:</label><br />
                  <input type="text" name="username" id="username" tabindex="1" 
                         class="field" value="<?php echo $this->escape($this->username);?>" /></p>
    	        <p><label for="password" class="top">Password:</label><br />
                  <input type="password" name="password" id="password" tabindex="2" 
                         class="field" value="" /></p>
    	        <p><input type="submit" name="cmdweblogin" class="button" value="Login" /></p>
  	        </fieldset>
            </form>
          </div>
        </div>      
<?php echo $this->render('footer.phtml'); ?>