      </div>
    </div>

    <!-- C. FOOTER AREA -->
    <div class="footer">
      <p>Copyright &copy; 2007  Щербо Максим Андреевич </p>
      <p class="credits"><a href="http://validator.w3.org/check?uri=referer" title="Validate XHTML code"><img src="<?php echo $this->baseUrl ?>/public/images/valid-xhtml10.small.png" /></a> <a href="http://jigsaw.w3.org/css-validator/" title="Validate CSS code"><img src="<?php echo $this->baseUrl ?>/public/images/valid-css.small.png" /></a> <a href="http://www.unicode.org" title="Unicode encoded"><img src="<?php echo $this->baseUrl ?>/public/images/utf-8.gif" /></a></p>
    </div>
  </div>
</body>
</html>
