<?php echo $this->render('header.phtml'); ?>
<h1 class="block"><?php echo $this->escape($this->title); ?></h1>
<div class="column1-unit">
  <table>
  <tr>
     <td><a href="<?php echo $this->baseUrl ?>/admin/reports/">Reports</a></td>
  </tr>
  <tr>
     <td><a href="<?php echo $this->baseUrl ?>/admin/users/">Manage Users</a></td>
  </tr>
  <tr>
     <td><a href="<?php echo $this->baseUrl ?>/admin/tests/">Manage Tests</a></td>
  </tr>
  </table>
</div>
<hr class="clear-contentunit" />
<?php echo $this->render('footer.phtml');?>