<?php echo $this->render('header.phtml'); ?>
<h1 class="block"><?php echo $this->escape($this->title); ?></h1>
<div class="column1-unit">
  <table>
  <tr>
      <th class="top" scope="col">Название теста</th>
      <th class="top" scope="col">Описание теста</th>
      <th class="top" scope="col">Действие</th>
  </tr>
  <?php foreach($this->tests as $test) { ?>
  <tr>
      <td><?php echo $this->escape($test['test_title']);?></td>
      <td><?php echo $this->escape($test['test_desc']);?></td>
      <td>
        <a href="<?php echo $this->baseUrl;?>/tests/index/start/id/<?php echo $test['test_id'];?>">Начать тест</a>
      </td>
  </tr>
  <?php } ?>
  </table>
</div>          
<hr class="clear-contentunit" />   
<?php echo $this->render('footer.phtml');?>