<?php echo $this->render('header.phtml'); ?>
<h1 class="block"><?php echo $this->escape($this->title); ?></h1>
<div class="column1-unit">
 <div class="testform">
   <form method="post" action="<?php echo $this->baseUrl ?>/tests/index/test">
    <fieldset>
      <table>
      <tr>
        <th class="top"><?php echo $this->escape($this->qst_curr + 1);?></th>
        <td><?php echo $this->question['qst_text'];?></td>
      </tr>
      <?php
      switch ($this->question['qst_type']) {
        case 1:
      ?>
      <tr>
        <th colspan="2">
          <textarea name="v[<?php echo $this->escape($this->qst_curr);?>][]"
                    class="textarea"><?php if ($this->is_show_ans) { echo $this->variants[0]['ans_text']; }?></textarea>
        </th>
      </tr>
      <?php
          break;
      case 2:
      ?>
      <?php foreach ($this->variants as $i => $variant) { ?>
      <tr>
        <th>
        <select name="v[<?php echo $this->escape($this->qst_curr);?>][]"
                  id="v<?php echo $i + 1;?>">
          <option  value="0">0</option>
          <?php for ($j = 1; $j <= sizeof($this->variants); $j++) { ?>
          <option value="<?php echo $j?>" <?php if ($this->is_show_ans &&  $variant['ans_is_correct'] == $j) { ?>selected="true"<?php }?>><?php echo $j?></option>
          <?php }?>
        </select>
        </th>
        <td><label for="v<?php echo $i + 1;?>"><?php echo $variant['ans_text']?></label></td>
      </tr>
      <?php }?>
      <?php
          break;
      case 3:
      ?>
      <?php foreach ($this->variants as $num => $variant) { ?>
      <tr>
        <th><input type="radio" name="v[<?php echo $this->escape($this->qst_curr);?>][]"
                 value="<?php echo $num + 1?>" id="v<?php echo $num + 1?>"
                 class="checkbox" <?php if ($this->is_show_ans && $variant['ans_is_correct']) { ?>checked="true"<?php }?> />
        </th>
        <td><label for="v<?php echo $num + 1?>"><?php echo $variant['ans_text']?></label></td>
      </tr>
      <?php } ?>
      <?php
          break;
      case 4:
      ?>
      <?php foreach ($this->variants as $num => $variant) { ?>
      <tr>
        <th><input type="checkbox" name="v[<?php echo $this->escape($this->qst_curr);?>][]"
                   value="<?php echo $num + 1?>" id="v<?php echo $num + 1?>"
                   class="checkbox" <?php if ($this->is_show_ans && $variant['ans_is_correct']) { ?>checked="true"<?php }?> />
        </th>
        <td><label for="v<?php echo $num + 1?>"><?php echo $variant['ans_text']?></label></td>
      </tr>
      <?php } ?>
      <?php
          break;
      case 5:
      ?>
      <?php for ($i = 1; $i <= sizeof($this->variants); $i++) { ?>
      <tr>
         <th><?php echo $i ?></th>
         <td>
          <select name="v[<?php echo $this->escape($this->qst_curr);?>][]" id="v<?php echo $i + 1;?>" class="combo">
            <option  value="0">Выберите порядок</option>
            <?php foreach ($this->variants as $j => $variant) { ?>
               <option value="<?php echo $j + 1?>"<?php if ($this->is_show_ans  && $variant['ans_is_correct'] == $i) { ?> selected="true" <?php }?>><?php echo $variant['ans_text']?></option>
             <?php  }?>
          </select>
        </td>
      </tr>
      <?php  } ?>
      <?php
          break;
      }
      ?>
      </table>
      <p><input type="submit" name="submit" class="button" value="Далее" /></p>
  	 </fieldset>
    </form>
  </div>
</div>
<hr class="clear-contentunit" />
<?php echo $this->render('footer.phtml');?>