<?php echo $this->render('header.phtml'); ?>
<h1 class="block"><?php echo $this->escape($this->title); ?></h1>
<div class="column1-unit">

  <table>
  <tr>
    <td><a href="<?php echo $this->baseUrl?>/admin">Admin Panel</a></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  </table>

  
  <table>
  <tr>
    <td><a href="<?php echo $this->baseUrl?>/admin/tests/add">Create Test</a></td>
  </tr>
  </table>
  
  <table>
  <tr>
      <th class="top" scope="col" width="30%">Test</th>
<?php /*      
      <th class="top" scope="col">Start Date</th>
      <th class="top" scope="col">End Date</th>
*/ ?>    
      <th class="top" scope="col" width="45%">Description</th>  
      <th class="top" scope="col" width="10%">Active</th>
      <th class="top" scope="col" width="15%">Action</th>
  </tr>
  <?php foreach($this->tests as $test) { ?>
  <tr>
      <td><?php echo $this->escape($test['test_title']);?></td>
      <td><?php echo $this->escape($test['test_desc']);?></td>      
<?php /*      
      <td><?php echo date('d.m.Y H:i:s', $this->escape($test['test_start_time']));?></td>
      <td><?php echo date('d.m.Y H:i:s', $this->escape($test['test_stop_time']));?></td>
*/ ?>      
      <td><?php echo $this->escape($test['test_is_enabled']);?></td>
      <td>
        <a href="<?php echo $this->baseUrl;?>/admin/tests/edit/id/<?php echo $test['test_id'];?>">Properties</a><br />
        <a href="<?php echo $this->baseUrl;?>/admin/questions/index/test/<?php echo $test['test_id'];?>">Questions</a><br />
        <a href="<?php echo $this->baseUrl;?>/admin/tests/delete/id/<?php echo $test['test_id'];?>" onclick="return confirm('Are you sure you want to delete this test?')">Delete</a>
        </td>
  </tr>
  <?php } ?>
  </table>
</div>          
<hr class="clear-contentunit" />   
<?php echo $this->render('footer.phtml');?>