<?php echo $this->render('header.phtml'); ?>
  <!-- Pagetitle -->
  <h1 class="pagetitle"><?php echo $this->escape($this->title);?></h1>

  <table class="navigation">
  <tr>
    <th><a href="<?php echo $this->baseUrl?>/admin">Admin Panel</a></th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
  </tr>
  </table>
  
  <table class="toolbar">
  <tr>
    <td><a href="<?php echo $this->baseUrl?>/admin/users/add"><img class="button" src="<?php echo $this->baseUrl?>/public/images/button-new-big.gif" alt="Add User" title="Add User" /></a></td>
<?php 
/*
    <td><img src="images/button-cross-big.gif" border=0 title="Delete users (for selected records)" style="cursor: hand;" onclick="f=document.usersForm;if (confirm('Are you sure want to delete selected users?')) { f.action='users.php?action=delete&confirmed=1';f.submit();}"></td>
*/
?>
    <td class="big">&nbsp;</td>
    <td>Page <?php echo $this->page_no?> of <?php echo $this->page_count?></td>

    <?php if ($this->page_no > 1) { ?>
    <td><a href="<?php echo $this->baseUrl?>/admin/users/index/pageno/1"><img class="button" src="<?php echo $this->baseUrl?>/public/images/button-first-big.gif" alt="First Page" title="Go to first page" /></a></td>
    <td><a href="<?php echo $this->baseUrl?>/admin/users/index/pageno/<?php echo $this->page_prev?>"><img class="button" src="<?php echo $this->baseUrl?>/public/images/button-prev-big.gif" alt="Previous Page" title="Go to previous page" /></a></td>
    <?php } else {?>
    <td><img class="button-inactive" src="<?php echo $this->baseUrl?>/public/images/button-first-big-inactive.gif" alt="First Page" title="Go to first page" /></td>
    <td><img class="button-inactive" src="<?php echo $this->baseUrl?>/public/images/button-prev-big-inactive.gif" alt="Previous Page" title="Go to previous page" /></td>
    <?php }?>
    
    <?php if($this->page_no < $this->page_count) { ?>
    <td><a href="<?php echo $this->baseUrl?>/admin/users/index/pageno/<?php echo $this->page_next?>"><img class="button" src="<?php echo $this->baseUrl?>/public/images/button-next-big.gif" alt="Next Page" title="Go to next page" /></a></td>
    <td><a href="<?php echo $this->baseUrl?>/admin/users/index/pageno/<?php echo $this->page_count?>"><img class="button" src="<?php echo $this->baseUrl?>/public/images/button-last-big.gif" alt="Last Page" title="Go to last page" /></a></td>
    <?php } else { ?>
    <td><img class="button-inactive" src="<?php echo $this->baseUrl?>/public/images/button-next-big-inactive.gif" alt="Next Page" title="Go to next page" /></td>
    <td><img class="button-inactive" src="<?php echo $this->baseUrl?>/public/images/button-last-big-inactive.gif" alt="Last Page" title="Go to last page" /></td>
    <?php } ?>
  </tr>
  </table>

 <table>
  <tr>
  <?php /* <th class="top" scope="col" width="2%">&nbsp;</th>*/ ?>
      <th class="top">Username</th>
      <th class="top">Last Name</th>
      <th class="top">First Name</th>
      <th class="top">Middle Name</th>
      <th class="top">e-mail</th>
      <th class="top">Active</th>
      <th class="top" colspan="2">Action</th>
  </tr>
  <?php foreach($this->users as $user) { ?>
  <tr>
      <?php /*<td><input type="checkbox" name="id[]" value="<?php echo $user['rst_id'];?>"/></td>*/?>
      <td><?php echo $this->escape($user['usr_login']);?></td>
      <td><?php echo $this->escape($user['usr_lastname']);?></td>
      <td><?php echo $this->escape($user['usr_firstname']);?></td>
      <td><?php echo $this->escape($user['usr_thirdname']);?></td>
      <td><?php echo $this->escape($user['usr_email']);?></td>
      <td><?php echo $this->escape($user['usr_is_enabled']);?></td>
      <td><a href="<?php echo $this->baseUrl;?>/admin/users/edit/id/<?php echo $user['usr_id'];?>"><img class="button" src="<?php echo $this->baseUrl?>/public/images/button-edit.gif" alt="Edit" title="Edit" /></a></td>
      <td><a href="<?php echo $this->baseUrl;?>/admin/users/delete/id/<?php echo $user['usr_id'];?>"><img  class="button" src="<?php echo $this->baseUrl?>/public/images/button-cross.gif" alt="Delete" title="Delete" /></a></td>
  </tr>
  <?php } ?>
  </table>

<?php
/*
    <table cellpadding=0 cellspacing=0 border=0 width="100%" style="background: url(images/toolbar-background.gif) repeat-x">
    <tr vAlign=center>
    <td width=2><img src="images/toolbar-left.gif" width=2 height=32></td>
    <td width=32><a href="users.php?action=create"><img src="images/button-new-big.gif" border=0 title="Create a new user"></a></td>
    <td width=3><img src="images/toolbar-separator.gif" width=3 height=32 border=0></td>
    <td width=32><img src="images/button-groups-big.gif" border=0 title="User groups (for selected records)" style="cursor: hand;" onclick="f=document.usersForm;f.action='users.php?action=groups';f.submit();"></td>
    <td width=3><img src="images/toolbar-separator.gif" width=3 height=32 border=0></td>
    <td width=32><img src="images/button-cross-big.gif" border=0 title="Delete users (for selected records)" style="cursor: hand;" onclick="f=document.usersForm;if (confirm('Are you sure want to delete selected users?')) { f.action='users.php?action=delete&confirmed=1';f.submit();}"></td>
    <td width="100%">&nbsp;</td>
    <td width=32><img src="images/button-first-big-inactive.gif" border=0 title="Go back to first page"></td>
    <td width=32><img src="images/button-prev-big-inactive.gif" border=0 title="Go back one page"></td>
    <td width=32><img src="images/button-next-big-inactive.gif" border=0 title="Go forward one page"></td>
    <td width=32><img src="images/button-last-big-inactive.gif" border=0 title="Go forward to last page"></td>
    <td width=2><img src="images/toolbar-right.gif" width=2 height=32></td>
    </tr>
    </table>
*/ ?>
<?php echo $this->render('footer.phtml');?>