<?php echo $this->render('header.phtml'); ?>
<h1 class="block"><?php echo $this->escape($this->title); ?></h1>    
<div class="column1-unit">
  <h1>Sorry, the requested page was not found.</h1>
  <p>
    This page is designed to help you fix this issue.<br />
    You can try one of the following methods:
  </p>

  <ul>
     <li>Go to <a href="<?php echo $this->baseUrl;?>/">Home Page</a></li>
     <li>Go to <a href="javascript:history.back(-1)">Previous Page</a></li>
  </ul>
 </div>     
<hr class="clear-contentunit" />   
<?php echo $this->render('footer.phtml');?>