<?php echo $this->render('header.phtml'); ?>
<h1 class="block"><?php echo $this->escape($this->title); ?></h1>
<div class="column1-unit">
  <div class="contactform">
    <form action="<?php echo $this->baseUrl?>/admin/questions/add" method="post">
    <fieldset> <legend>&nbsp;Question Parameters&nbsp;</legend>

      <p><label for="qst_is_enabled" class="left">Question Active:</label>
         <input type="checkbox" name="qst_is_enabled" id="qst_is_enabled"
                class="checkbox" checked="true" tabindex="1" />
      </p>

      <p><label for="qst_type" class="left">Question Type:</label>
         <select name="qst_type" id="qst_type" class="combo">
           <option value="1">Direct Input</option>
           <option value="2">Sequence</option>
           <option value="3">Multiple Choice</option>
           <option value="4">Multiple Answers</option>
           <option value="5">Order of Actions</option>
         </select>
      </p>

      <p><label for="qst_text" class="left">Question:</label>
         <textarea name="qst_text" id="qst_text"
                   cols="45" rows="5" tabindex="3"></textarea>
      </p>
    </fieldset>

    <fieldset> <legend>&nbsp;Answer Options&nbsp;</legend>

        <?php for ($i = 0; $i < 10; $i++) { ?>
        <p><label for="ans_text[<?php echo $i ?>]" class="left">Option <?php echo $i + 1 ?>:</label>
         <textarea name="ans_text[<?php echo $i ?>]" id="ans_text[<?php echo $i ?>]"
                   cols="45" rows="3"></textarea>
        </p>

         <p><label for="ans_correct[<?php echo $i ?>]" class="left">Correct:</label>
         <input type="checkbox" name="ans_correct[<?php echo $i ?>]" id="ans_correct[<?php echo $i ?>]"
                class="checkbox" />
         </p>
        <?php } ?>

        <input type="hidden" name="test_id" value="<?php echo $this->test_id?>" />
      <p>
        <input type="submit" name="cancel" id="cancel" class="button" value="Cancel" tabindex="9" />
        <input type="submit" name="submit" id="submit" class="button" value="Create" tabindex="10" />
      </p>
    </fieldset>
    </form>
  </div>
</div>
<hr class="clear-contentunit" />
<?php echo $this->render('footer.phtml');?>