<?php echo $this->render('header.phtml'); ?>
<h1 class="block"><?php echo $this->escape($this->title); ?></h1>
<div class="column1-unit">
<?php if (isset($this->result)) {?>
  <div class="testform">
  <fieldset>
  <form action="<?php echo $this->baseUrl ?>/admin/reports/delete" method="post">

  <table>
  <tr>
      <th class="top" scope="col" width="10%">Date</th>
      <th class="top" scope="col" width="30%">User</th>
      <th class="top" scope="col">Test</th>
      <th class="top" scope="col" width="10%">Time</th>
      <th class="top" scope="col">%</th>
      <th class="top" scope="col">Grade</th>
      <th class="top" scope="col">Exceeded</th>
  </tr>
  <tr>
      <td><?php echo date('d.m.Y H:i:s', $this->escape($this->result['rst_start_time']));?></td>
      <td>
        <?php echo $this->escape($this->result['usr_lastname']);?>
        <?php echo $this->escape($this->result['usr_firstname']);?>
        <?php echo $this->escape($this->result['usr_thirdname']);?>
      </td>
      <td><?php echo $this->escape($this->result['test_title']);?></td>
      <td><?php echo $this->escape($this->result['rst_time_spent']);?></td>
      <td><?php echo $this->escape($this->result['rst_points']);?></td>
      <td><?php echo $this->escape($this->result['rst_mark']);?></td>
      <td><?php echo $this->escape($this->result['rst_is_time_exceeded']);?></td>
  </tr>
  </table>



	<table>
	<tr>
	  <td>Are you sure you want to delete this test result?</td>
	</tr>
	<tr>
	  <td>
	  	<input type="hidden" name="id" value="<?php echo $this->escape($this->result['rst_id']);?>" />
		<input type="submit" name="del" value="Yes" />
		<input type="submit" name="del" value="No" />
	  </td>
	</tr>
	</table>
	<br />
  </form>
  </fieldset>
  </div>
  <?php } else { ?>
  <p>Result not found in database.</p>
  <?php }?>
</div>
<hr class="clear-contentunit" />
<?php echo $this->render('footer.phtml');?>