<?php echo $this->render('header.phtml'); ?>
<h1 class="block"><?php echo $this->escape($this->title); ?></h1>
<div class="column1-unit">


  <table>
  <tr>
    <td><a href="<?php echo $this->baseUrl?>/admin">Администрирование</a></td>
    <td><a href="<?php echo $this->baseUrl?>/admin/reports">Отчеты</a></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  </table>
 
  <form name="rst_form" action="<?php echo $this->baseUrl;?>/admin/reports/delete" method="post">
  <table>
  <tr>
  <?php /* <th class="top" scope="col" width="2%">&nbsp;</th>*/ ?>
      <th class="top" scope="col" width="10%">Дата</th>
      <th class="top" scope="col" width="20%">Пользователь</th>
      <th class="top" scope="col">Тест</th>
      <th class="top" scope="col" width="10%">Время</th>
      <th class="top" scope="col">%</th>
      <th class="top" scope="col">Оценка</th>
      <th class="top" scope="col">Превышено</th>
      <th class="top" scope="col" width="15%">Действие</th>
  </tr>
  <?php foreach($this->results as $result) { ?>
  <tr>
      <?php /*<td><input type="checkbox" name="id[]" value="<?php echo $result['rst_id'];?>"/></td>*/?>
      <td><?php echo date('d.m.Y H:i:s', $this->escape($result['rst_start_time']));?></td>
      <td>
        <?php echo $this->escape($result['usr_lastname']);?>
        <?php echo $this->escape($result['usr_firstname']);?>
        <?php echo $this->escape($result['usr_thirdname']);?>
      </td>
      <td><?php echo $this->escape($result['test_title']);?></td>
      <td><?php echo $this->escape($result['rst_time_spent']);?></td>
      <td><?php echo $this->escape($result['rst_points']);?></td>
      <td><?php echo $this->escape($result['rst_mark']);?></td>
      <td><?php echo $this->escape($result['rst_is_time_exceeded']);?></td>
      <td>
        <a href="<?php echo $this->baseUrl;?>/admin/reports/results/id/<?php echo $result['rst_id'];?>">Детально</a><br />
        <a href="<?php echo $this->baseUrl;?>/admin/reports/delete/id/<?php echo $result['rst_id'];?>">Удалить</a>
      </td>
  </tr>
  <?php } ?>
  </table>
   </form>
</div>          
<hr class="clear-contentunit" />   
<?php echo $this->render('footer.phtml');?>